language: cpp
os: osx
osx_image: xcode7.3
cache: ccache
before_install:
 - $TRAVIS_BUILD_DIR/supercollider/.travis/before-install-osx.sh --qt=true
before_script: 
 - mkdir $TRAVIS_BUILD_DIR/supercollider/BUILD
 - mkdir $TRAVIS_BUILD_DIR/BUILD
 - cd $TRAVIS_BUILD_DIR/supercollider/BUILD
 - cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt55`  ..
script:
 - cmake --build $TRAVIS_BUILD_DIR/supercollider/BUILD --target install --config RelWithDebInfo
 - cd $TRAVIS_BUILD_DIR/BUILD
 - cmake ..
 - make
 - auval -v aumf SCAU SCAU -r 4
